CREATE TABLE player_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL,
  account_id INTEGER,
  side TEXT,
  experience INTEGER,
  prestige_level INTEGER,
  pmc_sessions INTEGER,
  pmc_survived INTEGER,
  pmc_kills INTEGER,
  pmc_deaths INTEGER,
  pmc_killed_pmc INTEGER,
  scav_sessions INTEGER,
  scav_survived INTEGER,
  scav_kills INTEGER,
  scav_deaths INTEGER,
  scav_killed_pmc INTEGER,
  skills_json TEXT NOT NULL,
  mastering_json TEXT NOT NULL,
  achievements_count INTEGER NOT NULL DEFAULT 0,
  battle_pass_json TEXT NOT NULL,
  seasonal_rewards_completed INTEGER,
  seasonal_rewards_total INTEGER,
  uploaded_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);